### ISSUE TITLE
Program Errors Out

### ISSUE THREAD

**Issue by sekang2** [DaStraub/miPFinder#1]
Hi,

I can't quite figure out why the program is erroring out.  I am submitting the job through bash.

Here's my command:
```
python miPFinder_v1.py -f GCF_000002655.1_ASM265v1_protein.faa \
-S 5085.protein.links.detailed.v10.5.txt \
-d Pfam-A.hmm
```
All files are in the same folder.  I also did load Blast+, ClustalW2, and HMMER.  What am I missing?

```
The following have been reloaded with a version change:
  1) FFTW/3.3.7-gompi-2018a => FFTW/3.3.4-gompi-2016b
  2) GCC/6.4.0-2.28 => GCC/5.4.0-2.26
  3) GCCcore/6.4.0 => GCCcore/5.4.0
  4) GMP/6.1.2-GCCcore-6.4.0 => GMP/6.1.1-foss-2016b
  5) OpenBLAS/0.2.20-GCC-6.4.0-2.28 => OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1
  6) OpenMPI/2.1.2-GCC-6.4.0-2.28 => OpenMPI/1.10.3-GCC-5.4.0-2.26
  7) Python/2.7.14-foss-2018a => Python/2.7.14-foss-2016b
  8) SQLite/3.21.0-GCCcore-6.4.0 => SQLite/3.13.0-foss-2016b
  9) ScaLAPACK/2.0.2-gompi-2018a-OpenBLAS-0.2.20 => ScaLAPACK/2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1
 10) Tcl/8.6.8-GCCcore-6.4.0 => Tcl/8.6.5-foss-2016b
 11) binutils/2.28-GCCcore-6.4.0 => binutils/2.26-GCCcore-5.4.0
 12) bzip2/1.0.6-GCCcore-6.4.0 => bzip2/1.0.6-foss-2016b
 13) foss/2018a => foss/2016b
 14) gompi/2018a => gompi/2016b
 15) hwloc/1.11.8-GCCcore-6.4.0 => hwloc/1.11.3-GCC-5.4.0-2.26
 16) libffi/3.2.1-GCCcore-6.4.0 => libffi/3.2.1-foss-2016b
 17) libreadline/7.0-GCCcore-6.4.0 => libreadline/6.3-foss-2016b
 18) ncurses/6.0-GCCcore-6.4.0 => ncurses/6.0-foss-2016b
 19) numactl/2.0.11-GCCcore-6.4.0 => numactl/2.0.11-GCC-5.4.0-2.26
 20) zlib/1.2.11-GCCcore-6.4.0 => zlib/1.2.8-foss-2016b

/bin/sh: makeblastdb.exe: command not found
/bin/sh: del: command not found
Traceback (most recent call last):
  File "miPFinder_v1.py", line 87, in <module>
    args = vars(parser.parse_args())
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/argparse.py", line 1968, in _parse_known_args
    self._get_value(action, action.default))
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/argparse.py", line 2260, in _get_value
    result = type_func(arg_string)
  File "miPFinder_v1.py", line 20, in isBlast
    subprocess.check_output(('del testtest.*'), shell=True)
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'del testtest.*' returned non-zero exit status 127
```

**Comment by sekang2** [comment]
I was able to fix the error: `/bin/sh: makeblastdb.exe: command not found`

I included the full path to the file and it worked.  

I cannot figure out how to fix the error: `/bin/sh: del: command not found`

**Comment by sekang2** [comment]
fixed the error: `/bin/sh: del: command not found ` by replacing all 'del' command with 'rm'

Was getting error:` /bin/sh: copy: command not found` but I can't find 'copy' command in the script.  Submitted the script again and it worked but now getting a different error: 
```
Traceback (most recent call last):
  File "miPFinder_v1.py", line 178, in <module>
    q = raw_input('\ndelete /alignment and /blast folder? (Y/n/exit): ')
EOFError: EOF when reading a line
```

I'm told that I'm experiencing these errors because this script was written for windows and i'm trying to run it in linux.  As soon as I make this script work I will share it.

**Comment by sekang2** [comment]
Instead of submitting the job to /batch I ran the job in command line using a bash command.  This allowed me to answer the question whether to delete or not.  

```
delete /alignment and /blast folder? (Y/n/exit): Y
found 9630 sequences in GCF_000002655.1_ASM265v1_protein.faa
found 7491 >= 250 and 723 <= 140 and 1416 between (total: 9630 ).

write blast/small.fasta

write blast/big.fasta

copy GCF_000002655.1_ASM265v1_protein.faa blast\GCF_000002655.1_ASM265v1_protein.faa
/bin/sh: copy: command not found

ERROR, copy doesnt work... exit
cant create protein databases
```
I circled back to the error: `/bin/sh: copy: command not found` 

I need to change 'copy' to 'cp' for Linux, but I can't find the 'copy' command

**Comment by sekang2** [comment]
Fixed the copy error by editing script in splitdb_v13.py:

```
if os.path.isfile('blast/'+database) == False:
                copy = ('cp '+database+' blast//'+database)
                print '\n'+copy
subprocess.call(copy, shell=True)
```

Also had to edit the path to blastp and remove the .exe from file names

**Comment by sekang2** [comment]
Next Error:

```
"/usr/local/apps/eb/HMMER/3.1b2-foss-2016b/bin/hmmscan" -o hmmscan_terminal.txt --domtblout NA_hmmscandb.txt Pfam-A.hmm blast/big.fasta

Error: Failed to open binary auxfiles for Pfam-A.hmm: use hmmpress first

Traceback (most recent call last):
  File "miPFinder_v1.py", line 468, in <module>
    subprocess.check_output(hmmscanLINE, shell=True)
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '"/usr/local/apps/eb/HMMER/3.1b2-foss-2016b/bin/hmmscan" -o hmmscan_terminal.txt --domtblout NA_hmmscandb.txt Pfam-A.hmm blast/big.fasta' returned non-zero exit status 1

```

**Comment by sekang2** [comment]
To fix this next error I had to use the command: `hmmpress Pfam-A.hmm` 

Which generated several files:
```
Pressed and indexed 17929 HMMs (17929 names and 17929 accessions).
Models pressed into binary file:   Pfam-A.hmm.h3m
SSI index for binary model file:   Pfam-A.hmm.h3i
Profiles (MSV part) pressed into:  Pfam-A.hmm.h3f
Profiles (remainder) pressed into: Pfam-A.hmm.h3p
```

**Comment by sekang2** [comment]
Next Error:

```

found 9630 sequences in GCF_000002655.1_ASM265v1_protein.faa
found 1640031 lines in 5085.protein.links.detailed.v10.5.txt and 297488 passed filter: column 9 >= 400
Traceback (most recent call last):
  File "miPFinder_v1.py", line 471, in <module>
    domainsDB = domains(hmmscandb,HMMsearchDATABASE,fastasplit,evalueCUTOFF,cvalueCUTOFF,hmmscanPATH)
  File "/lustre1/sek53827/miPFinder/miPFinder-master/scripts/domains_v13.py", line 10, in domains
    if float(splitline[6]) <= evalueCUTOFF and float(splitline[11]) <= cvalueCUTOFF and float(splitline[12]) <= cvalueCUTOFF:#if domain is better than cuoff values
IndexError: list index out of range
```

**Comment by sekang2** [comment]
So.....

The miPFinder_v1.py script ran a LOT better when I used all the optional commands ( -S -d -m -p -a )

The most confusing part was generating the hmmscandb.txt but totally worth it. 

`hmmscan --domtblout hmmscandb.txt Pfam-A.hmm GCF_000002655.1_ASM265v1_protein.faa`
